# Generated by Django 4.1.3 on 2023-09-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kktechapp', '0005_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='tool_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
