# Generated by Django 4.1.3 on 2023-09-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kktechapp', '0006_alter_tools_tool_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='tool_image',
            field=models.ImageField(null=True, upload_to='Tool_image'),
        ),
    ]
