# Generated by Django 4.1.3 on 2023-09-01 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kktechapp', '0007_tools_tool_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroth',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kktechapp.projectmanagement'),
        ),
    ]
