# Generated by Django 4.1.3 on 2023-09-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kktechapp', '0008_projectgroth_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterials',
            name='rawmaterial_image',
            field=models.ImageField(null=True, upload_to='rawmaterial_image'),
        ),
    ]
