# Generated by Django 4.1.3 on 2023-09-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kktechapp', '0009_rawmaterials_rawmaterial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterials',
            name='rawmaterial_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
