# Generated by Django 4.1.3 on 2023-09-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kktechapp', '0011_projectmanagement_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='punch_stat_evening',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
