# Generated by Django 4.1.3 on 2023-09-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kktechapp', '0012_attendance_punch_stat_evening'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
