# Generated by Django 4.1.3 on 2023-09-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kktechapp', '0013_tools_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='evening_time',
            field=models.TimeField(default='00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='morning_time',
            field=models.TimeField(default='00:00:00', null=True),
        ),
    ]
