# Generated by Django 4.1.3 on 2023-09-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kktechapp', '0015_alter_attendance_evening_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='difference',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='working_hour',
            field=models.TimeField(null=True),
        ),
    ]
