# Generated by Django 4.1.3 on 2023-09-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kktechapp', '0016_attendance_difference_attendance_working_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='difference',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='working_hour',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
